# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-mecha-imx"
BBFILE_PATTERN_meta-mecha-imx = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-mecha-imx = "6"

LAYERDEPENDS_meta-mecha-imx = "core"
LAYERSERIES_COMPAT_meta-mecha-imx = "scarthgap"

MACHINE_EXTRA_RRECOMMENDS:append:imx8mp-lpddr4-evk = " kernel-module-nxp-wlan btnxpuartconf "
MACHINE_FEATURES:append:imx8mp-lpddr4-evk = " nxpiw612-sdio "
MACHINE_FIRMWARE:append:imx8mp-lpddr4-evk = " firmware-nxp-wifi-nxpiw612-sdio "

MACHINE_HAS_VIVANTE_KERNEL_DRIVER_SUPPORT = "1"
MACHINE_USES_VIVANTE_KERNEL_DRIVER_MODULE = "0"

KERNEL_DEVICETREE:append:use-nxp-bsp = " freescale/imx8mp-mecha-comet-m-gen6.dtb"

MACHINE_EXTRA_RRECOMMENDS:append:imx8mp-lpddr4-evk = " kernel-modules "

IMAGE_INSTALL += " stress-ng nxp-wlan-sdk packagegroup-qt6-imx iw i2c-tools v4l-utils alsa-state alsa-tools alsa-utils firmware-nxp-wifi busybox linux-firmware nxp-wlan-sdk kernel-module-nxp-wlan evtest packagegroup-fsl-isp packagegroup-core-base-utils kernel-modules isp-imx "

PACKAGE_INASTALL += " nxp-wlan-sdk firmware-nxp-wifi linux-firmware kernel-module-nxp-wlan "
